improve(slb): updated module slb and added example.
alibabacloud-automation/terraform-alicloud-slb pull request #13
Opened 2020-02-18 13:49 UTC by Lexsss

2020-02-18 14:41 UTC, zql-tqy commented on README-CN.md
> +本模板要求使用版本 Terraform 0.12.
本 Module 要求使用 Terraform 0.12 和 阿里云 Provider 1.56.0+。
中文readme标点要换成中文标点

2020-02-18 14:41 UTC, zql-tqy commented on README-CN.md
> +
提交问题的那个要加上

2020-02-18 14:41 UTC, zql-tqy commented on README.md
> +This module requires Terraform 0.12.
The Module requires Terraform 0.12 and Terraform Provider AliCloud 1.56.0+.

2020-02-18 14:41 UTC, zql-tqy commented on variables.tf
> +  description = "Whether to use an existing load balancer instance. If false, you can create a new one by set `create` to true."
`create` 需要 'create'

2020-02-19 07:41 UTC, xiaozhu36 requested changes

2020-02-19 07:41 UTC, xiaozhu36 commented on main.tf
> +      port        = servers.value.port
都改成 lookup的方式

2020-02-19 07:41 UTC, xiaozhu36 commented on variables.tf
> +  description = "Whether to use an existing load balancer instance. If false, you can create a new one by set 'create' to true."
"Whether to use an existing load balancer instance. If true, 'existing_slb_id' should not be empty. Also, you can create a new one by setting 'create =  true'."

2020-02-19 07:41 UTC, xiaozhu36 commented on variables.tf
> +  description = "Whether to create load balancer instance. If false, you can specify an existing load balancer instance by setting 'existing_slb_id' and set 'use_existing_slb' to true."
"Whether to create load balancer instance. If setting 'use_existing_slb = true' and 'existing_slb_id', it will be ignored.."

2020-02-19 07:41 UTC, xiaozhu36 commented on variables.tf
> +variable "use_uuid" {
use_uuid 不用这个参数了，直接保留 name的default就行，因为slb的name全局不是唯一的，可以重复设置。
不过可以把default值改成 tf-module-slb

2020-02-19 07:41 UTC, xiaozhu36 commented on variables.tf
> +variable "backend_servers" {
改成 servers_of_default_server_group

2020-02-19 07:41 UTC, xiaozhu36 commented on variables.tf
> +  }))
这个地方不用 object，直接用map就行，因为有default值，所有，有些参数不一定每次都设置。weight也设置一个default值，我看控制台上是100

2020-02-19 07:41 UTC, xiaozhu36 commented on variables.tf
> +variable "master_slave_servers" {
改成 servers_of_master_slave_server_group
object 改 map

2020-02-19 07:41 UTC, xiaozhu36 commented on variables.tf
> +variable "virtual_servers" {
servers_of_virtual_server_group
object 改 map

2020-02-19 12:51 UTC, xiaozhu36 requested changes

2020-02-19 12:51 UTC, xiaozhu36 commented on variables.tf
> +  type = list(map(string))
这三个参数你还是没改对啊。我的意思是每个参数中都应该支持server_ids，并且是一个stirng。如果resource中只有server_id，不支持server_ids，你要通过解析来支持

2020-02-19 14:53 UTC, xiaozhu36 requested changes

2020-02-19 14:53 UTC, xiaozhu36 commented on variables.tf
> +  default     = []
description 中要说清楚支持哪些字段

2020-02-19 14:53 UTC, xiaozhu36 commented on examples/master-slave-servers/main.tf
> +      server_id   = concat(module.ecs_instance.this_instance_id, ["", ""])[1]
这个字段值不对吧

2020-02-19 14:53 UTC, xiaozhu36 commented on examples/virtual-servers/main.tf
> +variable "region" {
servers-within-virtual-server-group

2020-02-19 14:53 UTC, xiaozhu36 commented on examples/master-slave-servers/main.tf
> +variable "region" {
servers-within-master-slave-server-group

2020-02-19 14:53 UTC, xiaozhu36 commented on examples/backend-server/main.tf
> +variable "region" {
servers-within-default-server-group

2020-02-19 14:53 UTC, xiaozhu36 commented on README-CN.md
> +      server_id   = "i-bp1xxxxxxxxxx1"
这个写法不对吧

2020-02-19 15:35 UTC, merged